# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_age', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('maximum_age', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=b'')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('writer', models.CharField(db_index=True, max_length=50)),
                ('genre', models.CharField(db_index=True, max_length=50)),
                ('keywords', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, db_index=True, default=None, null=True)),
                ('height', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('width', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('volumes', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('summary', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('state', models.CharField(choices=[('A', 'Active'), ('D', 'Disable')], db_index=True, default='A', max_length=1)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
